### ISSUE TITLE
android o's installer install os to seagate disk has "Failed to write bytes: device error"

### ISSUE THREAD

**Issue by advzhangyang** [intel/kernelflinger#15]
hello everyone,
I met a strange question.
Android o's installer install os to seagate disk has "Failed to write bytes: device error".
The steps of the matter are like this:
when the Android o's installer flash the system.img，it will report an error  "Failed to write bytes: device error".
But I changed the hard drive of a sata, it will work normally.

When I install this hard disk on other devices, the same OS can be installed normally.
So I guess it is timing or synchronization which it is not handled well.
At Iast, I find a workarround -> add 200ms delay to write function.
EFI_STATUS flash_write(VOID *data, UINTN size)
{
	EFI_STATUS ret;

	if (!gparti.bio)
		return EFI_INVALID_PARAMETER;

	if (!is_inside_partition(cur_offset, size)) {
		error(L"Attempt to write outside of partition [%ld %ld] [%ld %ld]",
				part_start, part_end, cur_offset, cur_offset + size);
		return EFI_INVALID_PARAMETER;
	}

        **_uefi_call_wrapper(BS->Stall,1,1000*100);_**
	ret = uefi_call_wrapper(gparti.dio->WriteDisk, 5, gparti.dio, gparti.bio->Media->MediaId, cur_offset, size, data);
        **_uefi_call_wrapper(BS->Stall,1,1000*100);_**

	if (EFI_ERROR(ret)) {
		efi_perror(ret, L"Failed to write bytes");
		return ret;
	}

	cur_offset += size;
	return EFI_SUCCESS;
}

Because of the time, I didn't continue to pursue it, but I want to know what happened to the installer. Can anyone help me?

thanks!

**Comment by tanminger** [comment]
Zhang:
  What is the hardware platform and BIOS info and what is the detail type of the storage you used and report error?

  BR/Tan Ming.

**Comment by advzhangyang** [comment]
Add a note:
When I install the seagate hard disk on other devices, the same OS can be installed normally.

hardware platform:
Intel(R) Atom(TM) Processor E3940 @ 1.60GHz

disk info:
seagate 1TB st1000lm048

BIOS info:
American megatrends  
core version:
5.12 x64

error log
flashing system.img 
Failed to write bytes: device error

**Comment by advzhangyang** [comment]
uefi version:
2.5

**Comment by tanminger** [comment]
I guess it maybe caused by the cache buffer of hard disk full, so after wait a while, then can write it successfully.

**Comment by advzhangyang** [comment]
But I changed to another x86 device, and it is still the Seagate's hard drive, it can work normally.

**Comment by tanminger** [comment]
How about the write disk performance?
If it is caused by cache buffer of hard disk full, then need the write speed of EFI application is higher than the write speed of physical disk.

**Comment by advzhangyang** [comment]
You have provided a new idea, thanks. It is a mechanical hard drive(Seagate disk) and another ssd disk is ok. I will continue to test, thank you

**Comment by jeremy-compostella** [comment]
This really looks like that the BIOS used on this device does not support
this disk properly. Kernelflinger is only using the UEFI disk IO interface
at this point. The delay that you added before the write could indeed give
enough time for disk to empty its cache or something like that.
Nevertheless, the BIOS disk IO driver is responsible of taking care of all
requirements to deal with a SATA disk. We are left with two options:
1. The BIOS had a bug
2. This disk had a problem which need to be workaround by software (the
BIOS here)

**Comment by tanminger** [comment]
The SATA hard disk has the internal cache, so maybe the cache full. The SSD in general has not internal cache, so has not the issue of internal cache full.

**Comment by advzhangyang** [comment]
Thank you everyone here, I will continue to track!
